In [2]:
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'pandas'

In [ ]:
batsman=pd.read_csv('dataset/ICC_test_bat.csv')

In [ ]:
batsman

,Player,Span,Mat,Inn,NO,Runs,HS,Avg,100,50,0,Player Profile
0,SR Tendulkar (INDIA),1989-2013,200,329,33,15921,248*,53.78,51,68,14,http://stats.espncricinfo.com/ci/content/playe...
1,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,41,62,17,http://stats.espncricinfo.com/ci/content/playe...
2,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,45,58,16,http://stats.espncricinfo.com/ci/content/playe...
3,R Dravid (ICC/INDIA),1996-2012,164,286,32,13288,270,52.31,36,63,8,http://stats.espncricinfo.com/ci/content/playe...
4,AN Cook (ENG),2006-2018,161,291,16,12472,294,45.35,33,57,9,http://stats.espncricinfo.com/ci/content/playe...
...,...,...,...,...,...,...,...,...,...,...,...,...
2996,CA Snedden (NZ),1947-1947,1,-,-,-,-,-,-,-,-,http://stats.espncricinfo.com/ci/content/playe...
2997,VN Swamy (INDIA),1955-1955,1,-,-,-,-,-,-,-,-,http://stats.espncricinfo.com/ci/content/playe...
2998,Usman Shinwari (PAK),2019-2019,1,-,-,-,-,-,-,-,-,http://stats.espncricinfo.com/ci/content/playe...
2999,CM Willoughby (SA),2003-2003,2,-,-,-,-,-,-,-,-,http://stats.espncricinfo.com/ci/content/playe...
3000,JW Wilson (AUS),1956-1956,1,-,-,-,-,-,-,-,-,http://stats.espncricinfo.com/ci/content/playe...

In [ ]:
batsman.shape

(3001, 12)

In [ ]:
batsman.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3001 entries, 0 to 3000
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Player          3001 non-null   object
 1   Span            3001 non-null   object
 2   Mat             3001 non-null   int64
 3   Inn             3001 non-null   object
 4   NO              3001 non-null   object
 5   Runs            3001 non-null   object
 6   HS              3001 non-null   object
 7   Avg             3001 non-null   object
 8   100             3001 non-null   object
 9   50              3001 non-null   object
 10  0               3001 non-null   object
 11  Player Profile  3001 non-null   object
dtypes: int64(1), object(11)
memory usage: 281.5+ KB

In [ ]:
batsman.columns

Index(['Player', 'Span', 'Mat', 'Inn', 'NO', 'Runs', 'HS', 'Avg', '100', '50',
       '0', 'Player Profile'],
      dtype='object')

In [ ]:
batsman.drop('Player Profile',axis=1,inplace=True)

In [ ]:
batsman.columns

Index(['Player', 'Span', 'Mat', 'Inn', 'NO', 'Runs', 'HS', 'Avg', '100', '50',
       '0'],
      dtype='object')

In [ ]:
batsman.isnull().sum()

Player    0
Span      0
Mat       0
Inn       0
NO        0
Runs      0
HS        0
Avg       0
100       0
50        0
0         0
dtype: int64

In [ ]:
batsman[batsman['100'].isnull()]

,Player,Span,Mat,Inn,NO,Runs,HS,Avg,100,50,0
2981,Ali Hussain Rizvi (PAK),1997-1997,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2982,PJ Allan (AUS),1965-1965,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2983,JC Clay (ENG),1935-1935,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2984,DJ Cullen (AUS),2006-2006,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2985,HT Dani (INDIA),1952-1952,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2986,Farrukh Zaman (PAK),1976-1976,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987,AB Howard (WI),1972-1972,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2988,A Khan (ENG),2009-2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2989,JCW MacBryan (ENG),1924-1924,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2990,LR Pierre (WI),1948-1948,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2991,V Rajindernath (INDIA),1952-1952,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2992,HD Read (ENG),1935-1935,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2993,CF Root (ENG),1926-1926,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2994,Shahid Mahboob (PAK),1989-1989,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2995,RC Shukla (INDIA),1982-1982,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2996,CA Snedden (NZ),1947-1947,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2997,VN Swamy (INDIA),1955-1955,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2998,Usman Shinwari (PAK),2019-2019,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999,CM Willoughby (SA),2003-2003,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3000,JW Wilson (AUS),1956-1956,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
batsman.replace('-',np.nan,inplace=True)

In [ ]:
batsman.isnull().sum()

Player     0
Span       0
Mat        0
Inn       20
NO        20
Runs      20
HS        20
Avg       88
100       20
50        20
0         20
dtype: int64

In [ ]:
batsman['Runs']=batsman['Runs'].fillna(0)
batsman['HS']=batsman['HS'].fillna(0)
batsman['100']=batsman['100'].fillna(0)
batsman['50']=batsman['50'].fillna(0)
batsman['0']=batsman['0'].fillna(0)

In [ ]:
batsman[batsman['Inn'].isnull()]

                       Player       Span  Mat  Inn   NO Runs HS  Avg 100 50  0
2981  Ali Hussain Rizvi (PAK)  1997-1997    1  NaN  NaN    0  0  NaN   0  0  0
2982           PJ Allan (AUS)  1965-1965    1  NaN  NaN    0  0  NaN   0  0  0
2983            JC Clay (ENG)  1935-1935    1  NaN  NaN    0  0  NaN   0  0  0
2984          DJ Cullen (AUS)  2006-2006    1  NaN  NaN    0  0  NaN   0  0  0
2985          HT Dani (INDIA)  1952-1952    1  NaN  NaN    0  0  NaN   0  0  0
2986      Farrukh Zaman (PAK)  1976-1976    1  NaN  NaN    0  0  NaN   0  0  0
2987           AB Howard (WI)  1972-1972    1  NaN  NaN    0  0  NaN   0  0  0
2988             A Khan (ENG)  2009-2009    1  NaN  NaN    0  0  NaN   0  0  0
2989       JCW MacBryan (ENG)  1924-1924    1  NaN  NaN    0  0  NaN   0  0  0
2990           LR Pierre (WI)  1948-1948    1  NaN  NaN    0  0  NaN   0  0  0
2991   V Rajindernath (INDIA)  1952-1952    1  NaN  NaN    0  0  NaN   0  0  0
2992            HD Read (ENG)  1935-1935    1  NaN  NaN    0  0  NaN   0  0  0
2993            CF Root (ENG)  1926-1926    3  NaN  NaN    0  0  NaN   0  0  0
2994     Shahid Mahboob (PAK)  1989-1989    1  NaN  NaN    0  0  NaN   0  0  0
2995        RC Shukla (INDIA)  1982-1982    1  NaN  NaN    0  0  NaN   0  0  0
2996          CA Snedden (NZ)  1947-1947    1  NaN  NaN    0  0  NaN   0  0  0
2997         VN Swamy (INDIA)  1955-1955    1  NaN  NaN    0  0  NaN   0  0  0
2998     Usman Shinwari (PAK)  2019-2019    1  NaN  NaN    0  0  NaN   0  0  0
2999       CM Willoughby (SA)  2003-2003    2  NaN  NaN    0  0  NaN   0  0  0
3000          JW Wilson (AUS)  1956-1956    1  NaN  NaN    0  0  NaN   0  0  0

In [ ]:
batsman['Inn']=batsman['Inn'].fillna('DNB')

In [ ]:
batsman.tail(20)

                       Player       Span  Mat  Inn   NO Runs HS  Avg 100 50  0
2981  Ali Hussain Rizvi (PAK)  1997-1997    1  DNB  NaN    0  0  NaN   0  0  0
2982           PJ Allan (AUS)  1965-1965    1  DNB  NaN    0  0  NaN   0  0  0
2983            JC Clay (ENG)  1935-1935    1  DNB  NaN    0  0  NaN   0  0  0
2984          DJ Cullen (AUS)  2006-2006    1  DNB  NaN    0  0  NaN   0  0  0
2985          HT Dani (INDIA)  1952-1952    1  DNB  NaN    0  0  NaN   0  0  0
2986      Farrukh Zaman (PAK)  1976-1976    1  DNB  NaN    0  0  NaN   0  0  0
2987           AB Howard (WI)  1972-1972    1  DNB  NaN    0  0  NaN   0  0  0
2988             A Khan (ENG)  2009-2009    1  DNB  NaN    0  0  NaN   0  0  0
2989       JCW MacBryan (ENG)  1924-1924    1  DNB  NaN    0  0  NaN   0  0  0
2990           LR Pierre (WI)  1948-1948    1  DNB  NaN    0  0  NaN   0  0  0
2991   V Rajindernath (INDIA)  1952-1952    1  DNB  NaN    0  0  NaN   0  0  0
2992            HD Read (ENG)  1935-1935    1  DNB  NaN    0  0  NaN   0  0  0
2993            CF Root (ENG)  1926-1926    3  DNB  NaN    0  0  NaN   0  0  0
2994     Shahid Mahboob (PAK)  1989-1989    1  DNB  NaN    0  0  NaN   0  0  0
2995        RC Shukla (INDIA)  1982-1982    1  DNB  NaN    0  0  NaN   0  0  0
2996          CA Snedden (NZ)  1947-1947    1  DNB  NaN    0  0  NaN   0  0  0
2997         VN Swamy (INDIA)  1955-1955    1  DNB  NaN    0  0  NaN   0  0  0
2998     Usman Shinwari (PAK)  2019-2019    1  DNB  NaN    0  0  NaN   0  0  0
2999       CM Willoughby (SA)  2003-2003    2  DNB  NaN    0  0  NaN   0  0  0
3000          JW Wilson (AUS)  1956-1956    1  DNB  NaN    0  0  NaN   0  0  0

In [ ]:
Play50= batsman=batsman[batsman['Mat']>100]
Play50

,Player,Span,Mat,Inn,NO,Runs,HS,Avg,100,50,0
0,SR Tendulkar (INDIA),1989-2013,200,329,33,15921,248*,53.78,51,68,14
1,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,41,62,17
2,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,45,58,16
3,R Dravid (ICC/INDIA),1996-2012,164,286,32,13288,270,52.31,36,63,8
4,AN Cook (ENG),2006-2018,161,291,16,12472,294,45.35,33,57,9
...,...,...,...,...,...,...,...,...,...,...,...
461,M Muralitharan (ICC/SL),1992-2010,133,164,56,1261,67,11.67,0,1,33
487,JM Anderson (ENG),2003-2019,150,211,89,1181,81,9.68,0,1,26
580,CA Walsh (WI),1984-2001,132,185,61,936,30*,7.54,0,0,43
730,M Ntini (SA),1998-2009,101,116,45,699,32*,9.84,0,0,21
766,GD McGrath (AUS),1993-2007,124,138,51,641,61,7.36,0,1,35

In [ ]:
Play50.tail(40)

,Player,Span,Mat,Inn,NO,Runs,HS,Avg,100,50,0
24,AJ Stewart (ENG),1990-2003,133,235,21,8463,190,39.54,15,45,14
25,DI Gower (ENG),1978-1992,117,204,18,8231,215,44.25,18,39,7
26,KP Pietersen (ENG),2005-2014,104,181,8,8181,227,47.28,23,35,10
27,G Boycott (ENG),1964-1982,108,193,23,8114,246*,47.72,22,42,10
29,ME Waugh (AUS),1991-2002,128,209,17,8029,153*,41.81,20,47,19
30,MA Atherton (ENG),1989-2001,115,212,7,7728,185*,37.69,16,46,20
31,IR Bell (ENG),2004-2015,118,205,24,7727,235,42.69,22,46,14
32,JL Langer (AUS),1993-2007,105,182,12,7696,250,45.27,23,30,11
33,MC Cowdrey (ENG),1954-1975,114,188,15,7624,182,44.06,22,38,9
34,CG Greenidge (WI),1974-1991,108,185,16,7558,226,44.72,19,34,11
36,MA Taylor (AUS),1989-1999,104,186,13,7525,334*,43.49,19,40,5
37,CH Lloyd (WI),1966-1985,110,175,14,7515,242*,46.67,19,39,4
38,DL Haynes (WI),1978-1994,116,202,25,7487,184,42.29,18,39,10
39,DC Boon (AUS),1984-1996,107,190,20,7422,200,43.65,21,32,16
41,G Kirsten (SA),1993-2004,101,176,15,7289,275,45.27,21,34,13
43,CH Gayle (WI),2000-2014,103,182,11,7214,333,42.18,15,37,15
44,SC Ganguly (INDIA),1996-2008,113,188,17,7212,239,42.17,16,35,13
46,SP Fleming (NZ),1994-2008,111,189,10,7172,274*,40.06,9,46,16
53,ST Jayasuriya (SL),1991-2007,110,188,14,6973,340,40.07,14,31,15
55,DB Vengsarkar (INDIA),1976-1992,116,185,22,6868,166,42.13,17,35,15
58,BB McCullum (NZ),2004-2016,101,176,9,6453,302,38.64,12,31,14
72,Saleem Malik (PAK),1982-1999,103,154,22,5768,237,43.69,15,29,12
74,CL Hooper (WI),1987-2002,102,173,15,5762,233,36.46,13,27,13
79,MV Boucher (ICC/SA),1997-2012,147,206,24,5515,125,30.3,5,35,17
89,N Kapil Dev (INDIA),1978-1994,131,184,15,5248,163,31.05,8,27,16
92,IT Botham (ENG),1977-1992,102,161,6,5200,208,33.54,14,22,14
107,DL Vettori (ICC/NZ),1997-2014,113,174,23,4531,140,30,6,23,20
118,IA Healy (AUS),1988-1999,119,182,23,4356,161*,27.39,4,22,18
146,SM Pollock (SA),1995-2008,108,156,39,3781,111,32.31,2,16,9
184,SCJ Broad (ENG),2007-2019,135,199,29,3158,169,18.57,1,12,35
185,SK Warne (AUS),1992-2007,145,199,17,3154,99,17.32,0,12,34
190,WPUJC Vaas (SL),1994-2009,111,162,35,3089,100*,24.32,1,13,12
203,Wasim Akram (PAK),1985-2002,104,147,19,2898,257*,22.64,3,7,17
250,A Kumble (INDIA),1990-2008,132,173,32,2506,110*,17.77,1,5,17
277,Harbhajan Singh (INDIA),1998-2015,103,145,23,2224,115,18.22,2,9,19
461,M Muralitharan (ICC/SL),1992-2010,133,164,56,1261,67,11.67,0,1,33
487,JM Anderson (ENG),2003-2019,150,211,89,1181,81,9.68,0,1,26
580,CA Walsh (WI),1984-2001,132,185,61,936,30*,7.54,0,0,43
730,M Ntini (SA),1998-2009,101,116,45,699,32*,9.84,0,0,21
766,GD McGrath (AUS),1993-2007,124,138,51,641,61,7.36,0,1,35